// Before publishing your new repository:
// 1. Write the readme file
// 2. Update the issues link in Contributing section in the readme file
// 3. Update the discussion link in config.yml file in .github/ISSUE_TEMPLATE directory

= HBS_03: Teragrep Metadata Using HBase

HBS_03 is a data replication tool that syncs data from MySQL to HBase using Teragrep's predefined schema.
It simplifies the process of migrating data from MySQL to HBase.

== Features

=== MySQL to HBase Data Replication
Replicates data from MySQL to HBase, ensuring consistency and efficiency.

=== Configurable Date Range
Allows users to specify a date range for data migration, offering flexibility in data selection.

=== Teragrep Schema Integration
Uses Teragrep's predefined schema to ensure that the data is mapped and replicated correctly between MySQL and HBase.

=== Automated Data Sync
Automates the process of syncing data from MySQL to HBase, reducing manual intervention.

=== Configurable Settings
Provides configurable options for customizing the migration process, such as date range and schema mappings.

== Documentation

See the official documentation on https://docs.teragrep.com[docs.teragrep.com].

== Limitations

Expects that you have a running instance of MySQL or MariaDB and
HBase the project can connect to.

Maven RPM (Red Hat Package Manager) packaging expects command line tool (rpm) to be installed

MariaDB is expected to have the Teragrep metadata schema.
Configured database user should have select permissions on journaldb, streamdb, bloomdb.

Smallest supported migration range is one date.

Executable job that starts until it finishes the migration range or exists with exception.
Exit code 0 for success and exit code 1 for exception.

== Options

You can configure the project using command line arguments.

=== Database option
Here we set options for the MySQL database configuration.
[source]
----
hbs.db.url=<database_url> // required
hbs.db.user=<database_user> // required
hbs.db.password=<database_password> // required
hbs.db.journaldb.name=<journaldb_name> // default 'journaldb'
hbs.db.streamdb.name=<streamdb_name> // default 'streamdb'
hbs.db.bloomdb.name=<bloomdb_name> // default 'bloomdb'
hbs.db.batch.size=<batch_size> // default '5000'
----

=== HBase options

Here we set configuration options for the hadoop configuration.
You can also provide a path to a .xml file for hadoop options

[source]
----
hbs.hadoop.logfile.table.name=<logfile_tablename> // default 'logfile'
hbs.hadoop.config.path=<path_to_xml_file> // you can give hadoop config using hbase-site.xml
hbs.hadoop.hbase.zookeeper.quorum=<localhost> // example how to give a hbase option
hbs.hadoop.* // set any option supported by hadoop.config.Configuration object
----

=== Migration options
Here we set the date range for the migration process.
Expects ISO format YYYY-MM-DD, dates are in system local time.
----
hbs.start=<start_date> // default minus 1 day from local date today
hbs.end=<end_date> // default local date today
----

== How to

After maven packaging the project, you can execute from the generated .jar file

Example script how to replicate between a date range between the dates 2010-01-01 and 2020-01-01.

[source]
----
java -jar hbs_03.jar hbs.db.username=user hbs.db.password=password
hbs.db.url=database_url hbs.hadoop.hbase.zookeeper.quorum=zookeeper_quorum
hbs.hadoop.hbase.zookeeper.property.clientPort=port hbs.db.journaldb.name=journaldb hbs.db.streamdb.name=streamdb
hbs.start=2010-01-01 hbs.end=2020-01-01
----

== Contributing

// Change the repository name in the issues link to match with your project's name

You can involve yourself with our project by https://github.com/teragrep/repo-template/issues/new/choose[opening an issue] or submitting a pull request.

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

=== Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories.

You need to submit the CLA only once. After submitting the CLA you can contribute to all Teragrep's repositories.
